
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async acceptWorthFixingFinding(findingId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_worth_fixing_finding", { findingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentListMessages() : Promise<Result<AgentMessageView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_messages") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentListPeers() : Promise<Result<AgentPeerView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentSendQuestion(recipientUserId: string, question: string) : Promise<Result<AgentMessageView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_send_question", { recipientUserId, question }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentSyncNow() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetActivate(presetId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_activate", { presetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetActivateManaged(providerKind: string, model: string) : Promise<Result<AiPresetView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_activate_managed", { providerKind, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetDelete(presetId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_delete", { presetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetDiscoverModels(providerKind: string, endpoint: string | null, apiKey: string | null) : Promise<Result<AiPresetModelsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_discover_models", { providerKind, endpoint, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetList() : Promise<Result<AiPresetView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetSave(name: string, providerKind: string, endpoint: string | null, model: string, apiKey: string | null) : Promise<Result<AiPresetView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_save", { name, providerKind, endpoint, model, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPresetTest(presetId: string) : Promise<Result<AiPresetView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_preset_test", { presetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pass Claude Code the short-lived authorization code shown by its provider
 * page. The code remains in memory and is never persisted by Dystil.
 */
async aiProviderCompleteClaudeLogin(authorizationCode: string) : Promise<Result<AiProviderStatusView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_complete_claude_login", { authorizationCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install the official CLI privately with Dystil's bundled Bun.
 */
async aiProviderInstall(provider: string) : Promise<Result<AiProviderStatusView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_install", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the provider-owned browser sign-in. No OAuth token passes through Dystil.
 */
async aiProviderLogin(provider: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_login", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sign out of Dystil's isolated provider session without touching a user's
 * separately installed global Codex or Claude Code credentials.
 */
async aiProviderLogout(provider: string) : Promise<Result<AiProviderStatusView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_logout", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List models exposed by the managed provider. Codex is discovered from the
 * signed-in account; Claude Code exposes its provider-maintained aliases.
 */
async aiProviderModels(provider: string) : Promise<Result<AiProviderModelView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_models", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read runtime installation and official runtime authentication state.
 */
async aiProviderStatus(provider: string) : Promise<Result<AiProviderStatusView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_status", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify the official runtime and its account session without invoking a model.
 *
 * A model request is intentionally not part of setup: remote queue and cold
 * start latency make it a poor connection diagnostic. The first inquiry is
 * the first request that lets the selected runtime query activity evidence.
 */
async aiProviderTest(provider: string) : Promise<Result<AiProviderStatusView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_provider_test", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the explicit social-media capture exceptions chosen during
 * onboarding, then refresh an active capture session so the new privacy
 * filters take effect immediately. A paused session stays paused.
 */
async applyOnboardingCapturePolicy(selectedSocialServices: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_onboarding_capture_policy", { selectedSocialServices }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authClearDeviceToken() : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_clear_device_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authClearSession() : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_clear_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authFetchProfile() : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_fetch_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authGetDeviceToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_device_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authGetSession() : Promise<Result<DystilUserSession | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authGetState() : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRegisterDevice() : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_register_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSignOut() : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authStoreSession(token: string) : Promise<Result<DystilAuthState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_store_session", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationCancel(runId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_cancel", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationCreate(markdown: string) : Promise<Result<AutomationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_create", { markdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationDelete(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_delete", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationDraft(request: string) : Promise<Result<AutomationDraftView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_draft", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationList() : Promise<Result<AutomationView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationListArtifacts(runId: string | null, limit: number | null) : Promise<Result<AutomationArtifactView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_list_artifacts", { runId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationListRuns(name: string | null, before: string | null, limit: number | null) : Promise<Result<AutomationRunView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_list_runs", { name, before, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationOpenDefinition(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_open_definition", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationRevealArtifact(artifactId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_reveal_artifact", { artifactId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationRunEvents(runId: string, beforeId: number | null, limit: number | null) : Promise<Result<AutomationRunEventView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_run_events", { runId, beforeId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationRunNow(name: string) : Promise<Result<AutomationRunView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_run_now", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationSaveDraft(draftId: string) : Promise<Result<AutomationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_save_draft", { draftId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async automationSetEnabled(name: string, enabled: boolean) : Promise<Result<AutomationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("automation_set_enabled", { name, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check only accessibility permission.
 */
async checkAccessibilityPermissionCmd() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_accessibility_permission_cmd");
},
/**
 * Check if Automation permission for Arc is already granted.
 * In production (.app bundle): uses direct FFI check (correct identity, no Terminal).
 * In dev mode: runs the binary itself via launchctl (detached from Terminal) so
 * macOS TCC checks the binary's own identity, not Terminal's.
 */
async checkArcAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_arc_automation_permission");
},
/**
 * Check if Arc browser is installed (macOS only)
 */
async checkArcInstalled() : Promise<boolean> {
    return await TAURI_INVOKE("check_arc_installed");
},
/**
 * Check if Automation permission is granted for all installed Chromium browsers.
 * Returns true only if ALL installed browsers have automation granted.
 */
async checkBrowsersAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_browsers_automation_permission");
},
/**
 * Check Input Monitoring permission (macOS only).
 *
 * Input Monitoring is a TCC category separate from Accessibility. Without
 * it the recorder can still capture clipboard (via NSPasteboard polling)
 * and app/window switches, but not keystrokes or clicks. Polling-safe —
 * uses the preflight variant that doesn't trigger the system prompt.
 */
async checkInputMonitoringPermissionCmd() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_input_monitoring_permission_cmd");
},
async checkPermission(permission: OSPermission) : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_permission", { permission });
},
/**
 * Check only screen recording permission (no dialog trigger).
 */
async checkScreenRecordingPermission() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_screen_recording_permission");
},
async cleanupWorthFixingDiagnostics(enhancedDiagnostics: boolean) : Promise<Result<WorthFixingCleanupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_worth_fixing_diagnostics", { enhancedDiagnostics }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeWindow(window: ShowRewindWindow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window", { window }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeOnboarding(onboardingData: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_onboarding", { onboardingData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy a frame deeplink (dystil://frame/N) to clipboard. Native API only.
 */
async copyDeeplinkToClipboard(frameId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_deeplink_to_clipboard", { frameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy arbitrary text to the system clipboard (native API, works in Tauri webview).
 * Use this instead of navigator.clipboard.writeText() which fails after async operations.
 */
async copyTextToClipboard(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_text_to_clipboard", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async correctWorthFixingFinding(findingId: string, correctionText: string, intent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correct_worth_fixing_finding", { findingId, correctionText, intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCacheFiles(paths: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cache_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Vault encryption is excluded from the Dystil product — always reports disabled.
 */
async disableKeychainEncryption() : Promise<Result<KeychainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_keychain_encryption") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disable click-through mode on the main overlay window (Windows only)
 * When disabled, the overlay receives mouse events normally
 */
async disableOverlayClickThrough() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_overlay_click_through") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dismissWorthFixingFinding(findingId: string, reason: DispositionKind) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_worth_fixing_finding", { findingId, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async doPermissionsCheck(initialCheck: boolean) : Promise<OSPermissionsCheck> {
    return await TAURI_INVOKE("do_permissions_check", { initialCheck });
},
/**
 * Vault encryption is excluded from the Dystil product — always reports disabled.
 */
async enableKeychainEncryption() : Promise<Result<KeychainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_keychain_encryption") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable click-through mode on the main overlay window (Windows only)
 * When enabled, mouse events pass through to windows below
 */
async enableOverlayClickThrough() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_overlay_click_through") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-assert the WKWebView as first responder for the current key panel.
 * Called from JS on pointer enter / window focus to ensure trackpad pinch
 * gestures (magnifyWithEvent:) reach the WKWebView for zoom handling.
 */
async ensureWebviewFocus() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_webview_focus") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register Dystil's read-only stdio sidecar in the user's own Codex CLI or
 * Claude Code configuration. This is intentionally separate from Dystil's
 * managed chat runtime and is only called after explicit UI consent.
 */
async externalMcpAdd(client: string) : Promise<Result<ExternalMcpSetupView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("external_mcp_add", { client }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusExistingWindow() : Promise<void> {
    await TAURI_INVOKE("focus_existing_window");
},
/**
 * Return the macOS bundle identifier of the running app
 * (e.g. `dystil`, `dystil.beta`, `dystil.dev`). The onboarding stuck-screen
 * surfaces this so users who switched build channels (prod ↔ beta ↔ dev) can
 * see they're looking at a *different* TCC record from the one they may have
 * already granted under a sibling bundle id.
 */
async getAppIdentifier() : Promise<string> {
    return await TAURI_INVOKE("get_app_identifier");
},
/**
 * Get the app-local focus/notification server port.
 */
async getAppServerConfig() : Promise<JsonValue> {
    return await TAURI_INVOKE("get_app_server_config");
},
/**
 * Read the current boot phase of the server. Used by the onboarding UI to
 * show progress ("updating database", "loading pipes", ...) while the HTTP
 * server is not yet listening — in particular during long DB migrations
 * where /health is unreachable.
 */
async getBootPhase() : Promise<BootPhaseSnapshot> {
    return await TAURI_INVOKE("get_boot_phase");
},
/**
 * Returns per-browser automation permission status for all installed Chromium browsers.
 */
async getBrowsersAutomationStatus() : Promise<BrowserAutomationStatus[]> {
    return await TAURI_INVOKE("get_browsers_automation_status");
},
async getBuildCapabilities() : Promise<BuildCapabilities> {
    return await TAURI_INVOKE("get_build_capabilities");
},
/**
 * Direct in-process health snapshot for the Dystil UI. This replaces the
 * legacy localhost Dystil HTTP/WebSocket health endpoint.
 */
async getCaptureHealth() : Promise<Result<CaptureHealth, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_capture_health") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the user's dystil cloud session JWT from `~/.dystil/
 * auth.json`. Returns None when the file is missing, malformed, or the
 * token field is empty.
 *
 * The settings store (`store.bin → user.token`) is the canonical
 * runtime cache for this token but is only populated after a fresh
 * in-app sign-in. `auth.json` is the durable on-disk copy written by
 * the pi-agent configuration flow — it survives store resets and dev-
 * mode launches where the in-memory user object hasn't been hydrated
 * yet. Used by the enterprise-policy hook to send the Bearer header
 * even when the in-app user object is still null.
 */
async getCloudToken() : Promise<string | null> {
    return await TAURI_INVOKE("get_cloud_token");
},
async getDiskUsage(forceRefresh: boolean | null, dataDir: string | null) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_disk_usage", { forceRefresh, dataDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEnv(name: string) : Promise<string> {
    return await TAURI_INVOKE("get_env", { name });
},
async getHardwareCapability() : Promise<HardwareCapability> {
    return await TAURI_INVOKE("get_hardware_capability");
},
/**
 * Returns the names of installed Chromium browsers that need Automation permission
 */
async getInstalledBrowsers() : Promise<string[]> {
    return await TAURI_INVOKE("get_installed_browsers");
},
async getKeychainStatus() : Promise<Result<KeychainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_keychain_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogFiles() : Promise<Result<LogFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaFile(filePath: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check all permissions and return which ones are missing
 */
async getMissingPermissions() : Promise<OSPermission[]> {
    return await TAURI_INVOKE("get_missing_permissions");
},
async getMonitors() : Promise<Result<MonitorDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_monitors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnboardingStatus() : Promise<Result<OnboardingStore, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_onboarding_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOtherWorthFixingFindings(cursor: string | null, limit: number) : Promise<Result<FindingPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_other_worth_fixing_findings", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read local cloud-sync consent. Defaults are fail-closed for both new and
 * existing installations because `syncConsent` is serde-defaulted.
 */
async getSyncConsent() : Promise<Result<SyncConsent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_consent") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorthFixingEvidence(findingId: string) : Promise<Result<WorthFixingEvidenceLine[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worth_fixing_evidence", { findingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorthFixingSummary() : Promise<Result<WorthFixingSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worth_fixing_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMainWindow() : Promise<void> {
    await TAURI_INVOKE("hide_main_window");
},
async hideNotificationPanel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_notification_panel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isCaptureRunning() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_capture_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if click-through is currently enabled (Windows only)
 */
async isOverlayClickThrough() : Promise<boolean> {
    return await TAURI_INVOKE("is_overlay_click_through");
},
async listCacheFiles() : Promise<Result<CacheFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_cache_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async localChatGetMessages(sessionId: string) : Promise<Result<LocalChatMessageView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_chat_get_messages", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async localChatListSessions() : Promise<Result<LocalChatSessionView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_chat_list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async localChatSend(sessionId: string, question: string) : Promise<Result<LocalChatMessageView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_chat_send", { sessionId, question }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpConnect() : Promise<Result<McpConnectionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_connect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpConnectionStatus() : Promise<Result<McpConnectionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_connection_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpDisconnect() : Promise<Result<McpConnectionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauthCancel(integrationId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_cancel", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauthConnect(integrationId: string, instance: string | null) : Promise<Result<OAuthStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_connect", { integrationId, instance }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauthDisconnect(integrationId: string, instance: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_disconnect", { integrationId, instance }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauthListInstances(integrationId: string) : Promise<Result<OAuthInstanceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_list_instances", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauthStatus(integrationId: string, instance: string | null) : Promise<Result<OAuthStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_status", { integrationId, instance }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open Google Calendar OAuth inside an in-app WebView.
 * Intercepts the dystil:// deep-link redirect so we don't rely on Safari
 * custom-scheme support.
 */
async openGoogleCalendarAuthWindow(authUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_google_calendar_auth_window", { authUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a local markdown note in Obsidian (if available), then fallback to OS default app.
 */
async openNotePath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_note_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPermissionSettings(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("open_permission_settings", { permission });
},
async openPipeWindow(port: number, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_pipe_window", { port, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openSearchWindow(query: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_search_window", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openWindowsShellTarget(target: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_windows_shell_target", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: re-encrypt store.bin after frontend saves.
 */
async reencryptStore() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reencrypt_store") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshTrayMenu() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_tray_menu") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Explicit refresh backend boundary. Normal background wakes use the same
 * durable engine; this command does not bypass admission or the daily cap.
 */
async refreshWorthFixing() : Promise<Result<WorthFixingRefreshResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_worth_fixing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request macOS Automation permission for Arc browser.
 * In production: triggers "dystil wants to control Arc" prompt via direct FFI.
 * In dev mode: runs the binary itself via launchctl to trigger the prompt with
 * the correct binary identity (not Terminal's). Also opens System Settings as fallback.
 */
async requestArcAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_arc_automation_permission");
},
/**
 * Request Automation permission for installed Chromium browsers that are already running.
 * Never force-launches browsers — only prompts for ones the user already has open.
 * Opens System Settings > Automation as fallback for browsers not running.
 */
async requestBrowsersAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_browsers_automation_permission");
},
/**
 * Request Input Monitoring permission (macOS only).
 *
 * Calls `cg_access::listen_request()` to trigger the system permission
 * flow. On first call this either shows the native prompt (if NotDetermined)
 * or silently no-ops (if already Denied — macOS doesn't re-prompt). For
 * reliability we also open System Settings → Input Monitoring so the user
 * can grant manually if the prompt didn't appear.
 *
 * Returns the post-request permission status so the UI can update without
 * waiting for the next poll.
 */
async requestInputMonitoringPermission() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("request_input_monitoring_permission");
},
async requestPermission(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("request_permission", { permission });
},
/**
 * Request automation permission for a single browser by name.
 * Returns the new status: "granted", "denied", or "not_asked".
 */
async requestSingleBrowserAutomation(browserName: string) : Promise<string> {
    return await TAURI_INVOKE("request_single_browser_automation", { browserName });
},
/**
 * Reset a permission using tccutil and re-request it
 * This removes the app from the TCC database and triggers a fresh permission request
 */
async resetAndRequestPermission(permission: OSPermission) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_and_request_permission", { permission }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hide the Main panel so the next shortcut press reconfigures it for the new mode.
 */
async resetMainWindow() : Promise<void> {
    await TAURI_INVOKE("reset_main_window");
},
async resetOnboarding() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetPermission(permission: OSPermission) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_permission", { permission }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize the Search NSPanel. Regular Tauri setSize doesn't work on NSPanels.
 */
async resizeSearchWindow(width: number, height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_search_window", { width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWorthFixingFinding(findingId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_worth_fixing_finding", { findingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostart(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push a fresh cloud-auth token into the running sidecar.
 *
 * The frontend invokes this on every sign-in (after `loadUser` writes
 * `settings.user`) and on sign-out (passing `None`). Without it, the
 * `Server.cloud_token` and `PiExecutor.user_token` captured at engine
 * boot would be permanent for the lifetime of the sidecar process —
 * users who signed in AFTER the engine started would stay on the
 * gateway's anonymous tier on every pipe run. Logout + log-in from
 * the webview alone does NOT restart the sidecar, which is why the
 * previous user-facing workaround was "fully quit the app from the tray."
 *
 * The pi-agent's `models.json` apiKey shares the same
 * `Arc<ArcSwap<Option<String>>>`, so one write here updates it on the
 * next pipe run.
 */
async setCloudToken(token: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cloud_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNativeTheme(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_native_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the final onboarding choice.
 */
async setOnboardingAiSetup(setup: OnboardingAiSetup) : Promise<Result<OnboardingStore, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_ai_setup", { setup }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnboardingStep(step: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_step", { step }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the user's explicit screenshot-capture choice and refresh an
 * active capture session so the new mode takes effect immediately. A paused
 * session stays paused. Enabling screenshots is rejected unless the platform
 * reports Screen Recording permission as granted (or not required).
 */
async setScreenshotCaptureEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_screenshot_capture_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist explicit local cloud-sync consent. Screenshot uploads are never
 * allowed independently of segment uploads.
 */
async setSyncConsent(consent: SyncConsent) : Promise<Result<SyncConsent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sync_consent", { consent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrayHealthIcon() : Promise<void> {
    await TAURI_INVOKE("set_tray_health_icon");
},
async setTrayUnhealthIcon() : Promise<void> {
    await TAURI_INVOKE("set_tray_unhealth_icon");
},
/**
 * Programmatically adjust a window's always-on-top level after creation.
 *
 * Tauri's JS `setAlwaysOnTop` can be unreliable for macOS panel-style
 * windows. For permission flows we need Dystil to stay normally
 * always-on-top, but temporarily drop below System Settings while the user is
 * granting permissions. On macOS this directly sets the underlying NSWindow
 * level: floating when enabled, normal when disabled.
 */
async setWindowAlwaysOnTopNative(label: string, alwaysOnTop: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_always_on_top_native", { label, alwaysOnTop }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWindowSize(window: ShowRewindWindow, width: number, height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_size", { window, width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindow() : Promise<void> {
    await TAURI_INVOKE("show_main_window");
},
async showNotificationPanel(payload: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_notification_panel", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showOnboardingWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_onboarding_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showPermissionRecoveryWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_permission_recovery_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showWindow(window: ShowRewindWindow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_window", { window }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Like `show_window` but forces macOS app activation first, so the target
 * window actually comes to the foreground when the caller is a
 * `NSNonactivatingPanelMask` panel (notifications, tray, etc.).
 *
 * Without this, clicking "Open" in the notification panel on macOS often
 * appears to do nothing: the non-activating panel style prevents the app
 * from becoming active, and overlay/fullscreen main modes rely on an
 * activate-aware `show_panel_visible(activate_app=true)` path that only
 * fires for `overlay_mode == "window"`. The window technically shows but
 * stays behind whatever app the user was in.
 *
 * Callers that represent explicit user intent (clicking Open on a
 * notification) should use this variant. Passive show-surface callers
 * should keep using `show_window` to avoid stealing focus unnecessarily.
 */
async showWindowActivated(window: ShowRewindWindow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_window_activated", { window }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the server (if not running) and capture.
 * This is the main entry point called by the frontend.
 */
async spawnCapture(overrideArgs: string[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_capture", { overrideArgs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start recording. Requires the server to be running.
 */
async startCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop recording without killing the server.
 * Pipes, memories, search, and the HTTP API remain accessible.
 */
async stopCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop capture AND server so the next spawn_capture does a full restart.
 * Called by updates and rollbacks.
 * The tray toggle uses stop_capture / start_capture to keep the server alive.
 */
async stopEngine() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_engine") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadFileToS3(filePath: string, signedUrl: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_file_to_s3", { filePath, signedUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: validate that a path is usable as a data directory.
 * Called from the frontend before saving the setting.
 */
async validateDataDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_data_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeBrowserLog(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("write_browser_log", { level, message });
},
async writeBrowserLogs(entries: BrowserLogEntry[]) : Promise<void> {
    await TAURI_INVOKE("write_browser_logs", { entries });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentEvidenceView = { label: string; localDate: string }
export type AgentMessageView = { messageId: string; conversationId: string; peerUserId: string; direction: string; kind: string; localStatus: string; text: string; evidence: AgentEvidenceView[]; createdAt: string }
export type AgentPeerView = { userId: string; displayName: string | null; email: string; agentStatus: string }
export type AiPresetModelsView = { models: string[]; detail: string }
export type AiPresetView = { id: string; name: string; providerKind: string; endpoint: string | null; model: string; active: boolean; credentialPresent: boolean; validationStatus: string; validationMessage: string | null; validatedAt: string | null }
export type AiProviderModelView = { id: string; displayName: string; description: string; isDefault: boolean }
export type AiProviderStatusView = { provider: string; state: string; installedVersion: string | null; authenticated: boolean | null; detail: string | null }
export type AuthMode = "individual" | "workspace"
export type AutomationArtifactView = { id: string; runId: string; automationName: string; relativePath: string; sizeBytes: number; mediaType: string; liveView: boolean; outputKind: string; contentJson: string | null; createdAt: string }
export type AutomationDraftView = { id: string; request: string; markdown: string; automation: AutomationView }
export type AutomationRunEventView = { id: number; runId: string; kind: string; message: string; createdAt: string }
export type AutomationRunView = { id: string; automationName: string; status: string; trigger: string; attempt: number; startedAt: string | null; finishedAt: string | null; provider: string | null; model: string | null; output: string | null; errorCategory: string | null; errorMessage: string | null }
export type AutomationView = { name: string; title: string; description: string | null; enabled: boolean; triggerType: string; triggerDetail: string | null; path: string }
export type BootPhaseSnapshot = {
/**
 * One of: idle | starting | migrating_database |
 * starting_pipes | ready | error
 */
phase: string;
/**
 * Human-readable detail to show the user (may be long-running hint)
 */
message: string | null;
/**
 * Present only when phase == "error"
 */
error: string | null;
/**
 * Unix epoch seconds when the current phase was entered. Lets the UI
 * show "X minutes" on slow migrations.
 */
sinceEpochSecs: number }
/**
 * Per-browser automation status: "granted", "denied", or "not_asked".
 * Also includes whether the browser is currently running.
 */
export type BrowserAutomationStatus = { name: string; status: string; running: boolean }
export type BrowserLogEntry = { level: string; message: string }
export type BuildCapabilities = { cloudAvailable: boolean; authMode: AuthMode; cloudBaseUrl: string | null; officialBuild: boolean }
export type CacheFile = { path: string; label: string; size_bytes: number }
export type Cadence = "none" | "daily" | "weekly" | "monthly"
export type CaptureHealth = { status: string; status_code: number; last_frame_timestamp: string | null; last_ui_timestamp: string | null; frame_status: string; ui_status: string; message: string }
export type Credits = { amount: number }
export type DispositionKind = "accepted" | "saved" | "not_a_problem" | "leave_it" | "close_but"
export type DystilAuthState = { status: string; session: DystilUserSession | null; user: DystilUserProfile | null; device_token_present: boolean; error: string | null }
export type DystilUserOrg = { id: string; name: string | null; slug: string | null; roles: string[] }
export type DystilUserProfile = { id: string; email: string | null; name: string | null; image: string | null; org: DystilUserOrg | null }
export type DystilUserSession = { session_token: string | null; expires_at: string | null }
export type ExternalMcpSetupView = { client: string; detail: string }
export type FindingPage = { items: WorthFixingCard[]; nextCursor: string | null }
export type HandoffType = "prompt" | "saved_prompt" | "existing_capability" | "runbook"
export type HardwareCapability = { hasGpu: boolean; cpuCores: number; totalMemoryGb: number; recommendedEngine: string; reason: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type KeychainStatus = { state: string }
export type LocalChatMessageView = { id: string; sessionId: string; role: string; mode: string; question: string | null; answer: string | null; status: string; citationsJson: string | null; provider: string | null; model: string | null; elapsedMs: number | null; errorCode: string | null; createdAt: string }
export type LocalChatSessionView = { id: string; title: string; updatedAt: string }
export type LogFile = { name: string; path: string; modified_at: number }
export type McpConnectionStatus = { connected: boolean; detail: string }
export type MonitorDevice = { id: number; stableId: string; name: string; isDefault: boolean; width: number; height: number }
export type OAuthInstanceInfo = { instance: string | null; display_name: string | null }
export type OAuthStatus = { connected: boolean; display_name: string | null; needs_attention?: boolean }
export type OSPermission = "screenRecording" | "accessibility" | "automation" | "inputMonitoring" | "calendar"
export type OSPermissionStatus = "notNeeded" | "empty" | "granted" | "denied"
export type OSPermissionsCheck = { screenRecording: OSPermissionStatus; accessibility: OSPermissionStatus }
export type OnboardingAiSetup = { choice: string }
export type OnboardingStore = { isCompleted: boolean; completedAt: string | null;
/**
 * Current step in onboarding flow (login, intro, usecases, status)
 * Used to resume after app restart (e.g., after granting permissions)
 */
currentStep?: string | null;
/**
 * The capability selected in the final onboarding step. This records a
 * local preference only; provider credentials live in their own stores.
 */
aiSetupChoice?: string | null }
/**
 * A single schedule rule: a day-of-week + time range + what to record.
 */
export type ScheduleRule = {
/**
 * Day of week: 0 = Monday, 6 = Sunday
 */
dayOfWeek: number;
/**
 * Start time in "HH:MM" (24h format, local time)
 */
startTime: string;
/**
 * End time in "HH:MM" (24h format, local time)
 */
endTime: string;
/**
 * What to record: "all" or "screen_only"
 */
recordMode: string }
export type SettingsStore =
/**
 * All recording/capture config lives here. Flattened so the JSON shape
 * is unchanged for the visual/accessibility settings that remain supported.
 */
({
/**
 * Disable all screen capture.
 */
disableVision: boolean;
/**
 * Disable the timeline / rewind feature. When true, the engine skips
 * timeline-only work: warming the hot frame cache from the DB at startup
 * and buffering captured frames into the in-memory hot cache that
 * only the timeline streaming endpoint reads.
 */
disableTimeline?: boolean;
/**
 * Specific monitor IDs to capture.
 */
monitorIds: string[];
/**
 * Capture from all connected monitors.
 */
useAllMonitors: boolean;
/**
 * Video quality preset: "low", "balanced", "high", "max".
 */
videoQuality: string;
/**
 * Maximum width for stored snapshots. Images wider than this are downscaled
 * (preserving aspect ratio) before JPEG encoding. 0 = no limit (store at
 * native resolution). Default: 1920.
 */
maxSnapshotWidth?: number;
/**
 * Skip the background JPEG->MP4 snapshot compaction worker.
 * Use when the MP4 timeline UI is not used, e.g. task-mining tools
 * that consume frame_text / ui_events only.
 * Side effect: JPEGs are not compacted, so disk usage depends on retention.
 */
disableSnapshotCompaction?: boolean;
/**
 * Skip the v2 meeting detector watcher (5s-interval process / AX scan).
 * Use when meeting detection is not consumed (task-mining, headless analysis,
 * agents that read frame_text and ui_events only) — avoids the
 * constant process enumeration + AX tree walk cost.
 * Side effect: meeting-related DB rows are not generated.
 */
disableMeetingDetector?: boolean;
/**
 * Apps / meeting services to exclude from automatic meeting detection
 * while leaving detection on for everything else. Case-insensitive
 * substring match against the running app's name/process AND the matched
 * detection profile's identifiers (native names + browser URL patterns),
 * so an entry can be what the user sees ("Discord") or a service domain
 * ("meet.google.com"). Use when one app trips the detector spuriously
 * (an always-open Teams, a Discord call you don't want logged) but you
 * still want Zoom/Meet/etc. detected. Empty = detect all known apps.
 */
ignoredMeetingApps?: string[];
/**
 * Legacy key-trigger override retained for settings compatibility.
 * Recording sessions keep keyboard-triggered capture on; raw key/text DB
 * rows are controlled separately by `disableKeyboardCapture`.
 */
captureOnKeystroke?: boolean | null;
/**
 * Override `EventDrivenCaptureConfig::capture_on_clipboard`.
 * None = engine default (false). When true, clipboard changes fire a
 * paired capture. Clipboard DB rows are still controlled separately by
 * `disableClipboardCapture`.
 */
captureOnClipboard?: boolean | null;
/**
 * Override `UiRecorderConfig::capture_scroll`.
 * None = engine default (false). When true, scroll wheel events are
 * recorded into `ui_events` so the `ScrollBurstTracker` can fire a
 * `ScrollStop` trigger at burst-end and link the last scroll row to
 * the resulting frame. Off by default — wheel ticks fire at ~60Hz
 * and inflate the table fast.
 */
captureScroll?: boolean | null;
/**
 * Prioritize mouse/keyboard input latency over a11y event completeness.
 * Opt-in master switch for the three coordinated optimizations defined on
 * `UiCaptureConfig.prioritize_input_latency`.
 */
prioritizeInputLatency?: boolean;
/**
 * OS thread priority for a11y extraction threads when `prioritize_input_latency`
 * is true. Values: "normal" / "below_normal" / "lowest" / "idle".
 */
extractionThreadPriority?: string;
/**
 * Skip UIA tree captures within this many ms after the most recent input.
 * 0 disables. Ignored when `prioritize_input_latency` is false.
 */
pauseExtractionOnInputMs?: number;
/**
 * Window titles to exclude from capture.
 */
ignoredWindows: string[];
/**
 * Window titles to exclusively capture (empty = capture all).
 */
includedWindows: string[];
/**
 * URLs to exclude from capture.
 */
ignoredUrls?: string[];
/**
 * Automatically detect and skip incognito / private browsing windows.
 */
ignoreIncognitoWindows: boolean;
/**
 * Experimental: pause screen capture when a DRM-protected streaming app
 * (Netflix, Disney+, etc.) or a remote-desktop client (Omnissa/VMware
 * Horizon) is focused. These apps blank their windows while screen
 * recording is active.
 * Off by default; engine-only pause (no full app shutdown).
 */
pauseOnDrmContent?: boolean;
/**
 * Skip persisting clipboard rows/content in the UI recorder. Defaults to
 * `true` (clipboard DB capture OFF) — passwords / API keys / private keys
 * frequently pass through the clipboard. Clipboard operations can still
 * wake event-driven capture when `captureOnClipboard` is enabled.
 */
disableClipboardCapture?: boolean;
/**
 * Skip persisting keyboard / typed-text rows in the UI recorder.
 * Defaults to `true` (keyboard DB capture OFF). Keyboard events still
 * wake event-driven capture, and the accessibility tree + OCR still
 * capture on-screen text so Rewind/Ask keep working.
 * Opt in to keyboard DB rows via the "Capture keyboard" toggle.
 */
disableKeyboardCapture?: boolean;
/**
 * Redact personally identifiable information from transcriptions.
 */
usePiiRemoval: boolean;
/**
 * Enable the async PII reconciliation worker. When `true`, a
 * background task runs after capture and OVERWRITES PII in the
 * source columns of `frames.frame_text` and `ui_events.text_content`. Raw
 * secrets are gone after the worker processes the row — that's
 * the contract of the user-facing "AI PII removal" toggle.
 * Off by default; capture path is unaffected either way. See
 * `dystil-redact` for the full design.
 */
asyncPiiRedaction?: boolean;
/**
 * Where text AI PII redaction actually runs. The user-facing
 * "AI PII removal" toggle is one knob.
 *
 * - `"local"` (default): on-device ONNX models. Privacy by
 * construction — pixels and text never leave the box. Slower,
 * especially on weak hardware (~1-3 s per text row, ~60-180 ms
 * per frame).
 * - `"tinfoil"`: send to the dystil Tinfoil enclave (H200,
 * confidential compute). Much faster (~30-100 ms per row /
 * frame). Data leaves the device but is end-to-end encrypted
 * into an attested confidential-compute enclave that even
 * Tinfoil ops can't read into. Requires network +
 * `DYSTIL_PRIVACY_FILTER_API_KEY` (or the cloud auth key).
 *
 * Note on attestation: the proper attested-transport client
 * (Tinfoil's secure-client SDK) is Go/Python/JS-only at time of
 * writing. The Rust adapter currently uses plain HTTPS — which
 * gives confidentiality vs. the network but NOT vs. a malicious
 * Tinfoil operator. Tracked separately; structured for swap-in.
 */
piiBackend?: string;
/**
 * Which PII classes the AI redaction workers actually rewrite
 * when `asyncPiiRedaction` is on.
 * Canonical snake_case `SpanLabel` names (e.g.
 * `["secret", "email", "person"]`). The models detect every
 * class but only these are removed — the rest is *value* (a
 * searchable timeline). Defaults to `["secret"]`, the safety
 * baseline; `secret` is always treated as included regardless of
 * what's stored (see dystil-redact `parse_allow_list`). The
 * Settings UI surfaces a curated subset (Names, Emails, Phones,
 * Addresses, Sensitive) as opt-in checkboxes.
 */
piiRedactionLabels?: string[];
/**
 * Dystil cloud user ID. Empty string means not logged in.
 * Kept as String (not Option) to match existing store.bin schema.
 */
userId: string;
/**
 * Power mode preference: "auto", "performance", "battery_saver".
 * Previously stored in SettingsStore.extra["powerMode"].
 */
powerMode?: string | null;
/**
 * Use Chinese mirror for Hugging Face model downloads.
 */
useChineseMirror: boolean;
/**
 * Enable AI workflow event detection (cloud feature, requires subscription).
 * When enabled, classifies desktop activity and triggers event-based pipes.
 */
enableWorkflowEvents?: boolean;
/**
 * Detected hardware tier ("high", "mid", "low").
 * Set once on first launch; `None` for existing installs (treated as High).
 */
deviceTier?: string | null;
/**
 * Enable work-hours schedule (when false, records 24/7 as usual)
 */
scheduleEnabled?: boolean;
/**
 * Per-day schedule rules (only used when schedule_enabled is true)
 */
scheduleRules?: ScheduleRule[] }) &
/**
 * Catch-all for fields added by the frontend (e.g. chatHistory)
 * that the Rust struct doesn't know about. Without this, `save()` would
 * serialize only known fields and silently wipe frontend-only data.
 */
({ [key in string]: null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue } }) & { isLoading: boolean; devMode: boolean; ocrEngine: string; dataDir: string; autoStartEnabled: boolean; platform: string; user: User;
/**
 * Explicit, local permission for cloud synchronization. This is never
 * inferred from login/device state or remote policy.
 */
syncConsent?: SyncConsent;
/**
 * Unique device ID for AI usage tracking (generated on first launch)
 */
deviceId?: string;
/**
 * Auto-install updates and restart when a new version is available.
 * When disabled, users must click "update now" in the tray menu.
 */
autoUpdate?: boolean;
/**
 * Auto-update store-installed pipes that haven't been locally modified.
 */
autoUpdatePipes?: boolean;
/**
 * Timeline overlay mode: "fullscreen" (floating panel above everything) or
 * "window" (normal resizable window with title bar).
 */
overlayMode?: string;
/**
 * Allow screen recording apps to capture the overlay.
 * Disabled by default so the overlay doesn't appear in dystil's own recordings.
 */
showOverlayInScreenRecording?: boolean;
/**
 * Show restart notifications when visual capture stalls.
 * Disabled by default for now until the stall detector is more reliable.
 */
showRestartNotifications?: boolean;
/**
 * When true, apply macOS vibrancy effect to the sidebar for a translucent look.
 */
translucentSidebar?: boolean;
/**
 * When true (default), hide model "thinking" reasoning blocks in the chat
 * transcript. The model still emits them server-side; we just don't
 * render the collapsible block in the UI.
 */
hideThinkingBlocks?: boolean;
/**
 * UI theme: "light", "dark", or "system".
 */
uiTheme?: string;
/**
 * Windows-only: when true, clicking the X on the Home window hides it to
 * the system tray (and removes it from the taskbar) instead of minimizing.
 * Read by the CloseRequested handler in main.rs. Default off (historical
 * minimize-to-taskbar behavior).
 */
minimizeToTrayOnClose?: boolean }
export type ShowRewindWindow = "Main" | { Home: { page: string | null } } | { Search: { query: string | null } } | "Onboarding" | "PermissionRecovery"
export type SyncConsent = { segments: boolean; screenshots: boolean }
export type User = { id: string | null; name: string | null; email: string | null; image: string | null; token: string | null; api_key: string | null; credits: Credits | null; bio: string | null; website: string | null; contact: string | null; credits_balance: number | null }
export type WorthFixingCard = { findingId: string; label: string; claim: string; whyWorthFixing: string; handoffType: HandoffType; handoffTitle: string; handoffPreview: string; occurrenceCount: number; cadence: Cadence; evidenceAvailable: boolean }
export type WorthFixingCleanupResult = { removedFiles: number; removedBytes: number; retainedBytes: number; enhancedDiagnostics: boolean }
export type WorthFixingEvidenceLine = { evidenceId: string; occurredAt: string; app: string | null; description: string; available: boolean }
export type WorthFixingRefreshResult = { status: string; jobId: string | null; opportunitiesChanged: number; findingsCreated: number }
export type WorthFixingSummary = { selected: WorthFixingCard[]; eligibleCount: number; watchingCount: number; pendingObservationCount: number; processing: boolean; staleEvidenceCount: number; providerReady: boolean; lastSuccessfulWakeAt: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
