"use client";

import { useState } from "react";
import { ChipRow, DataChips, PrivacyCard, TextAction } from "../page-primitives";

export function Privacy({ onOpenSettings }: { onOpenSettings: () => void }) {
  const [notice, setNotice] = useState("");
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  return <div className="mx-auto max-w-[1124px] pb-10"><h1 className="text-[29px] font-medium tracking-[-0.02em] text-[#1a1c20]">What stays on this computer</h1><p className="mt-[10px] max-w-[680px] text-[18px] leading-[1.65] text-[#60636b]">Everything Dystil has read is in one folder on this machine. Nothing has been sent anywhere, and there is no copy of it to ask for.</p><div className="mt-[18px] rounded-[12px] bg-[#f3f8f5] px-[18px] py-[14px] text-[17px] leading-[1.55] text-[#60636b]">This page is the whole picture in one place. Anything you want to change is one click away in <button type="button" className="text-[#0f6e56]" onClick={onOpenSettings}>Settings</button>.</div>
    <PrivacyCard accent title="What never leaves">Everything Dystil reads about your work, and everything it has worked out from it.<br />Where it lives: <span className="text-[#1a1c20]">~/Library/Application Support/Dystil</span><div className="mt-[14px] flex gap-5"><TextAction onClick={() => showNotice("Opening Dystil’s local folder…")}>Open that folder</TextAction><TextAction onClick={() => showNotice("Opening the source code…")}>Read the code that does this</TextAction></div></PrivacyCard>
    <PrivacyCard title="What does leave, and only because you chose it" action={<TextAction onClick={onOpenSettings}>Change in Settings</TextAction>}>You are using your own Anthropic key, so anything Dystil needs a model for goes to Anthropic and is billed to you. It never comes to us.</PrivacyCard>
    <PrivacyCard title="Never read, and there is no switch for it">No job needs these, and getting them wrong would matter too much. They are skipped in the code, not in a setting.<ChipRow items={["Passwords and credentials", "Banking and payments", "Health", "Dating and faith apps", "Private browsing windows"]} /></PrivacyCard>
    <PrivacyCard title="Off unless you say otherwise" action={<TextAction onClick={onOpenSettings}>Change in Settings</TextAction>}>Personal for most people, work for some. You have turned one of these on.<ChipRow items={["Job boards and CVs, on", "Personal messaging", "Personal email", "HR and legal portals", "Payroll and salary"]} firstActive /></PrivacyCard>
    <PrivacyCard title="Delete what it has read">Deleting removes it from this computer, because that is the only place it was.<div className="mt-[14px] flex flex-wrap gap-[10px]">{["Everything from today", "One app or site", "A date range", "Everything, and start over"].map((item, index) => <button key={item} type="button" onClick={() => showNotice(index === 3 ? "Everything Dystil has read would be deleted. This cannot be undone." : `${item} deleted from this computer.`)} className={`rounded-[9px] border px-[15px] py-[9px] text-[15px] ${index === 3 ? "border-[#d9b4ae] text-[#9a4a3c]" : "border-[#e1e1dc] text-[#30333a]"}`}>{item}</button>)}</div></PrivacyCard>
    <section className="mt-[28px] border-t border-[#e7e7e2] pt-[24px]"><h2 className="text-[22px] font-medium text-[#1a1c20]">How your work is read</h2><p className="mt-[7px] max-w-[690px] text-[17px] leading-[1.6] text-[#60636b]">This is what Dystil thinks it is looking at. If any of it is wrong, or is none of its business, take it out.</p><p className="mt-[5px] max-w-[690px] text-[16px] leading-[1.6] text-[#92969e]">Removing something here deletes it and stops it being used again. Turning a source off, below, stops Dystil reading it at all.</p><DataChips label="The work you do" items={["Client reporting", "Month-end close", "Invoicing", "Hiring"]} /><DataChips label="People your work passes through" items={["Priya", "Rahul", "The Halloran team"]} /><div className="mt-[22px] rounded-[12px] border border-[#e7e7e2] bg-white px-[20px] py-[18px]"><div className="flex justify-between gap-5"><div><h3 className="text-[18px] font-medium">Apps and sites it has come across</h3><p className="mt-1 text-[16px] text-[#60636b]">Forty-one in total. These six are where nearly all of your work happens.</p></div><TextAction onClick={onOpenSettings}>Manage in Settings</TextAction></div><ChipRow items={["Excel", "Outlook", "docs.google.com", "Slack", "Xero", "app.hubspot.com", "Instagram", "open.spotify.com"]} /></div></section>{notice && <div role="status" className="fixed bottom-[28px] left-1/2 z-20 -translate-x-1/2 rounded-[9px] bg-[#1a1c20] px-[18px] py-[11px] text-[15px] text-white">{notice}</div>}</div>;
}
