"use client";

import { useState } from "react";
import { readyFixes } from "../data";
import { PageHeading } from "../page-primitives";

export function ReadyToUse({ onAsk }: { onAsk: () => void }) {
  const [expanded, setExpanded] = useState<string | null>(readyFixes[0].id);
  const [approved, setApproved] = useState<string[]>([]);
  return <div className="mx-auto max-w-[1124px]"><PageHeading title="Three fixes are ready." description="Dystil found repeatable work it can prepare for you. Nothing runs until you review and approve it." /><section className="mt-[38px]"><div className="border-b border-[#dad8d2] pb-[12px]"><h2 className="text-[20px] font-medium text-black">Ready now</h2></div><div className="divide-y divide-[#e1dfd9] border-b border-[#dad8d2]">{readyFixes.map((fix) => { const isExpanded = expanded === fix.id; const isApproved = approved.includes(fix.id); return <article key={fix.id} className="py-[20px]"><div className="grid grid-cols-[108px_minmax(0,1fr)_auto] items-start gap-[22px]"><p className={`mt-[3px] flex items-center gap-[8px] text-[13px] font-medium ${isApproved ? "text-[#6c726f]" : "text-[#087b5f]"}`}><span className={`h-[7px] w-[7px] rounded-full ${isApproved ? "bg-[#8f9692]" : "bg-[#12a77a]"}`} />{isApproved ? "Approved" : "Fix ready"}</p><div><h3 className="text-[20px] font-medium leading-[1.3] text-[#151716]">{fix.title}</h3><p className="mt-[5px] text-[16px] leading-[1.5] text-[#596069]">{fix.description}</p><p className="mt-[9px] text-[13px] text-[#8a8f95]">{fix.evidence}</p></div><button type="button" onClick={() => setExpanded(isExpanded ? null : fix.id)} className="mt-[1px] min-w-[86px] rounded-[9px] border border-[#d4d2cc] bg-white px-[14px] py-[9px] text-[14px] font-medium text-[#3d4247] transition-colors hover:border-[#8db7a8] hover:text-[#087b5f] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#087b5f]">{isExpanded ? "Close" : "Review"}</button></div>{isExpanded && <div className="ml-[130px] mt-[17px] rounded-[12px] bg-[#f5faf7] px-[18px] py-[16px]"><p className="text-[14px] font-medium text-[#22302b]">What Dystil will do</p><ol className="mt-[10px] grid gap-[7px]">{fix.steps.map((step, index) => <li key={step} className="flex gap-[10px] text-[14px] leading-[1.5] text-[#5c6460]"><span className="text-[#0f6e56]">{index + 1}.</span><span>{step}</span></li>)}</ol><div className="mt-[15px] flex items-center gap-[14px]"><button type="button" disabled={isApproved} onClick={() => setApproved((current) => current.includes(fix.id) ? current : [...current, fix.id])} className="rounded-[9px] bg-[#087b5f] px-[16px] py-[9px] text-[14px] font-medium text-white hover:bg-[#06634d] disabled:bg-[#d7ddd9] disabled:text-[#78817c]">{isApproved ? "Approved" : "Approve this fix"}</button><button type="button" onClick={() => setExpanded(null)} className="text-[14px] text-[#6a706d] hover:text-[#222624]">Not now</button></div></div>}</article>; })}</div></section><button type="button" onClick={onAsk} className="mt-[24px] text-[15px] font-medium text-[#087b5f] hover:text-[#055d49]">Want Dystil to look at something else? Ask for a fix →</button></div>;
}
