"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AtSign, ChevronRight, Clock3, Loader2, MessageSquarePlus, Pause, Play, Send, Settings2 } from "lucide-react";
import { DystilBrand } from "@/components/dystil-brand";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";

type Card = { windowId: string; title: string; summary: string; applications: string[]; startTime: string; endTime: string; status: string; lastObservedState: string };
type Peer = { userId: string; displayName: string | null; email: string; agentStatus: string };
type AgentMessage = { messageId: string; peerUserId: string; direction: string; kind: string; localStatus: string; text: string; evidence: Array<{ label: string; localDate: string }> };
export type ChatSession = { id: string; title: string; updatedAt: string };
export type Chat = { id: string; conversationId: string; question: string; mode: "local" | "team"; answer?: string | null; status?: "pending" | "complete" | "failed"; citations?: Array<{ label: string; localDate: string }>; provider?: string | null; model?: string | null; elapsedMs?: number | null };

export function ChatShell({ userName, userEmail, recording, toggling, onToggleRecording, screenshotEnabled, onScreenshotChange, screenshotBusy, peers, agentMessages, cards, loadingCards, sessions, onLoadSession, onSendLocal, onAskPeer, onLogout, loggingOut, version }: {
  userName: string; userEmail: string; recording: boolean; toggling: boolean; onToggleRecording: () => void; screenshotEnabled: boolean; onScreenshotChange: (value: boolean) => void; screenshotBusy: boolean;
  peers: Peer[]; agentMessages: AgentMessage[]; cards: Card[]; loadingCards: boolean; sessions: ChatSession[]; onLoadSession: (sessionId: string) => Promise<Chat[]>; onSendLocal: (sessionId: string, question: string) => Promise<Chat>; onAskPeer: (peerId: string, question: string) => Promise<void>; onLogout: () => void; loggingOut: boolean; version: string;
}) {
  const [page, setPage] = useState<"chat" | "timeline" | "history" | "settings">("chat");
  const [input, setInput] = useState("");
  const [mentionOpen, setMentionOpen] = useState(false);
  const [selectedPeer, setSelectedPeer] = useState<Peer | null>(null);
  const [busy, setBusy] = useState(false);
  const [loadingSession, setLoadingSession] = useState(false);
  const [activeConversationId, setActiveConversationId] = useState(() => crypto.randomUUID());
  const [chats, setChats] = useState<Chat[]>([]);
  const threadEnd = useRef<HTMLDivElement>(null);
  const activeSession = sessions.find((session) => session.id === activeConversationId);

  useEffect(() => { threadEnd.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [chats, busy]);
  useEffect(() => {
    // Fast Refresh can preserve component state across a frontend/backend
    // mismatch. A completed conversation without a persisted session is stale,
    // so discard it rather than presenting it as real local history.
    if (!busy && chats.length && !activeSession) {
      setChats([]);
      setActiveConversationId(crypto.randomUUID());
    }
  }, [activeSession, busy, chats.length]);
  const visiblePeers = useMemo(() => peers.filter((peer) => !input.includes("@") || `${peer.displayName} ${peer.email}`.toLowerCase().includes(input.replace(/^.*@/, "").toLowerCase())), [peers, input]);
  const newChat = () => { setPage("chat"); setInput(""); setSelectedPeer(null); setMentionOpen(false); setActiveConversationId(crypto.randomUUID()); setChats([]); };
  const openSession = async (sessionId: string) => {
    setPage("chat"); setActiveConversationId(sessionId); setLoadingSession(true); setChats([]);
    try { setChats(await onLoadSession(sessionId)); } finally { setLoadingSession(false); }
  };
  const submit = async () => {
    let question = input.trim();
    if (selectedPeer) { const prefix = `@${selectedPeer.displayName || selectedPeer.email.split("@")[0]}`; if (question.startsWith(prefix)) question = question.slice(prefix.length).trim(); }
    if (!question || busy) return;
    setBusy(true);
    try {
      if (selectedPeer) {
        const chat: Chat = { id: crypto.randomUUID(), conversationId: activeConversationId, question: `@ ${selectedPeer.displayName || selectedPeer.email.split("@")[0]} · ${question}`, mode: "team", status: "pending" };
        setChats((current) => [...current, chat]);
        await onAskPeer(selectedPeer.userId, question);
      } else {
        const optimistic: Chat = { id: crypto.randomUUID(), conversationId: activeConversationId, question, mode: "local", status: "pending" };
        setChats((current) => [...current, optimistic]);
        try {
          const stored = await onSendLocal(activeConversationId, question);
          setChats((current) => current.map((chat) => chat.id === optimistic.id ? stored : chat));
        } catch (error) {
          const answer = error instanceof Error ? error.message : "Dystil could not save or answer this question.";
          setChats((current) => current.map((chat) => chat.id === optimistic.id ? { ...chat, status: "failed", answer } : chat));
        }
      }
      setInput(""); setMentionOpen(false); setSelectedPeer(null);
    } finally { setBusy(false); }
  };
  const choosePeer = (peer: Peer) => { setSelectedPeer(peer); setInput(`@${peer.displayName || peer.email.split("@")[0]} `); setMentionOpen(false); };
  const title = page === "chat" ? activeSession?.title || "New chat" : { timeline: "Timeline", history: "Chat history", settings: "Settings" }[page];

  return <main className="flex h-dvh overflow-hidden bg-background text-foreground"><div className="flex h-full w-full overflow-hidden bg-background">
    <aside className="flex w-[270px] shrink-0 flex-col border-r border-border/80 bg-[#f8faf7] p-4 max-md:w-[66px] max-md:px-2">
      <DystilBrand className="justify-start px-2 pb-5 max-md:justify-center max-md:px-0 [&_span:last-child]:max-md:hidden" highlightY />
      <Button className="justify-start gap-2 rounded-xl bg-foreground px-3 text-background hover:bg-foreground/90 max-md:justify-center max-md:px-0" onClick={newChat}><MessageSquarePlus className="h-4 w-4" /><span className="max-md:hidden">New chat</span></Button>
      <nav className="mt-5 grid gap-1"><button onClick={() => setPage("timeline")} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm text-muted-foreground hover:bg-accent hover:text-foreground max-md:justify-center max-md:px-0", page === "timeline" && "bg-accent font-medium text-foreground")}><Clock3 className="h-4 w-4" /><span className="max-md:hidden">Timeline</span></button></nav>
      <div className="mt-6 max-md:hidden"><p className="px-2 text-[10px] font-semibold uppercase tracking-[.16em] text-muted-foreground">Recent chats</p><div className="mt-2 grid gap-1">{sessions.slice(0, 5).map((session) => <button key={session.id} onClick={() => void openSession(session.id)} className={cn("truncate rounded-lg px-2 py-2 text-left text-sm text-muted-foreground hover:bg-accent hover:text-foreground", session.id === activeConversationId && page === "chat" && "bg-accent font-medium text-foreground")}>{session.title}</button>)}{!sessions.length && <p className="px-2 py-2 text-xs text-muted-foreground">Your conversations will appear here.</p>}</div><button className="mt-2 flex items-center gap-1 px-2 text-xs text-primary hover:underline" onClick={() => setPage("history")}>View all history <ChevronRight className="h-3 w-3" /></button></div>
      <div className="mt-auto flex items-center gap-2 border-t border-border/80 pt-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{userName.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1 max-md:hidden"><p className="truncate text-xs font-medium">{userName}</p><p className="truncate text-[11px] text-muted-foreground">{userEmail}</p></div><button className="rounded-md p-2 text-muted-foreground hover:bg-accent hover:text-foreground" onClick={() => setPage("settings")}><Settings2 className="h-4 w-4" /></button></div>
    </aside>
    <section className="flex min-w-0 flex-1 flex-col"><header className="flex h-[68px] items-center justify-between border-b border-border/60 px-5 sm:px-8"><b className="max-w-[60%] truncate text-sm">{title}</b><span className="flex items-center gap-2 text-xs text-muted-foreground"><i className={cn("h-2 w-2 rounded-full", recording ? "bg-primary shadow-[0_0_0_3px_hsl(var(--primary)/.14)" : "bg-muted-foreground")} />{recording ? "Recording locally" : "Capture paused"}</span></header>
      {page === "chat" && <div className="flex min-h-0 flex-1 flex-col"><div className="flex flex-1 overflow-auto"><div className="m-auto w-full max-w-[800px] px-6 py-10 text-center">{!chats.length && !loadingSession && <><DystilBrand className="mb-8" highlightY vertical large /><h1 className="text-3xl font-semibold tracking-[-.055em] sm:text-4xl">What can I help you remember?</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-muted-foreground">Ask about your work, or type <b>@</b> to ask a teammate’s Dystil. Raw accessibility text never appears here.</p><div className="mt-6 flex flex-wrap justify-center gap-2">{["What did I work on today?", "Find the Grafana page I used Tuesday", "Prepare a concise standup update"].map((q) => <button key={q} className="rounded-full border border-border bg-card px-3 py-2 text-xs text-muted-foreground hover:border-primary/50 hover:bg-accent" onClick={() => setInput(q)}>{q}</button>)}</div></>}
        {loadingSession && <div className="py-16 text-sm text-muted-foreground"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Opening conversation…</div>}
        {chats.map((chat, index) => <div key={chat.id} className="mb-7 text-left"><div className="ml-auto max-w-[78%] rounded-2xl rounded-tr-sm bg-primary px-4 py-3 text-sm text-primary-foreground">{chat.question}</div><div className="mt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">{chat.mode === "team" ? "Teammate’s Dystil" : "Dystil"}</p>{chat.mode === "team" ? <TeamAnswer messages={agentMessages} peers={peers} /> : <LocalAnswer chat={chat} />}</div>{index < chats.length - 1 && <div className="my-7 border-t border-border/60" />}</div>)}<div ref={threadEnd} /></div></div>
        <Composer input={input} setInput={setInput} busy={busy} submit={submit} mentionOpen={mentionOpen} setMentionOpen={setMentionOpen} visiblePeers={visiblePeers} choosePeer={choosePeer} /></div>}
      {page === "timeline" && <Timeline cards={cards} loading={loadingCards} />}
      {page === "history" && <HistoryPage sessions={sessions} onOpen={(sessionId) => void openSession(sessionId)} />}
      {page === "settings" && <SettingsPage recording={recording} toggling={toggling} onToggle={onToggleRecording} screenshots={screenshotEnabled} onScreenshot={onScreenshotChange} screenshotBusy={screenshotBusy} userName={userName} userEmail={userEmail} onLogout={onLogout} loggingOut={loggingOut} version={version} />}
    </section>
  </div></main>;
}

function Composer({ input, setInput, busy, submit, mentionOpen, setMentionOpen, visiblePeers, choosePeer }: { input: string; setInput: (value: string) => void; busy: boolean; submit: () => Promise<void>; mentionOpen: boolean; setMentionOpen: (value: boolean) => void; visiblePeers: Peer[]; choosePeer: (peer: Peer) => void }) { return <div className="mx-auto w-full max-w-[820px] px-5 pb-6"><div className="relative rounded-2xl border border-border bg-card p-1.5 shadow-[0_10px_30px_rgba(55,82,61,.08)]"><div className="relative"><input value={input} onChange={(event) => { const value = event.target.value; setInput(value); if (value.includes("@")) setMentionOpen(true); }} onKeyDown={(event) => { if (event.key === "Enter") void submit(); }} placeholder="Ask Dystil anything about your work…" className="h-12 w-full bg-transparent px-3 pr-12 text-sm outline-none placeholder:text-muted-foreground" /><button onClick={() => void submit()} disabled={busy || !input.trim()} className="absolute right-1 top-1 grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground disabled:opacity-40">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</button></div>{mentionOpen && <div className="absolute bottom-[70px] left-0 w-full max-w-[390px] rounded-xl border border-border bg-card p-2 shadow-xl"><p className="px-2 py-1 text-[10px] font-semibold uppercase tracking-[.15em] text-muted-foreground">Ask a teammate’s Dystil</p>{visiblePeers.length ? visiblePeers.map((peer) => <button key={peer.userId} onClick={() => choosePeer(peer)} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-accent"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary-muted text-[10px] font-semibold text-primary">{(peer.displayName || peer.email).slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><b className="block text-xs">{peer.displayName || peer.email.split("@")[0]}</b><span className="block truncate text-[11px] text-muted-foreground">{peer.email}</span></span><span className="text-[10px] text-primary">{peer.agentStatus === "connected" ? "● connected" : "available"}</span></button>) : <p className="p-2 text-xs text-muted-foreground">No compatible teammates in your organization yet.</p>}</div>}</div><p className="flex justify-between px-1 pt-2 text-[11px] text-muted-foreground"><span><AtSign className="mr-1 inline h-3 w-3" />Ask a teammate</span><span>Enter to send</span></p></div> }
function LocalAnswer({ chat }: { chat: Chat }) { if (chat.status === "pending") return <div className="rounded-2xl border border-border bg-card p-4 text-sm text-muted-foreground"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Finding the relevant local work and writing an answer…</div>; return <div className="rounded-2xl border border-border bg-card p-4"><p className={cn("text-sm leading-6", chat.status === "failed" && "text-destructive")}>{chat.answer || "Dystil could not generate an answer."}</p>{chat.citations?.length ? <div className="mt-3 border-t border-border/60 pt-3 text-xs text-muted-foreground"><b className="mb-1 block text-[10px] uppercase tracking-wider">Based on local work</b>{chat.citations.map((item) => <p key={`${item.label}-${item.localDate}`}>• {item.label} — {item.localDate}</p>)}</div> : null}{chat.provider ? <p className="mt-3 text-[10px] text-muted-foreground">Generated with {chat.provider}{chat.model ? ` · ${chat.model}` : ""}</p> : null}</div> }
function TeamAnswer({ messages, peers }: { messages: AgentMessage[]; peers: Peer[] }) { const answer = messages.find((message) => message.kind === "response"); if (!answer) return <div className="rounded-2xl border border-border bg-card p-4 text-sm text-muted-foreground"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Searching and generating an answer…</div>; const name = peers.find((peer) => peer.userId === answer.peerUserId)?.displayName || "Teammate"; return <div className="rounded-2xl border border-border bg-card p-4"><p className="text-sm leading-6">{answer.text}</p>{answer.evidence.length ? <div className="mt-3 border-t border-border/60 pt-3 text-xs text-muted-foreground"><b className="mb-1 block text-[10px] uppercase tracking-wider">Evidence from {name}’s local work</b>{answer.evidence.map((item) => <p key={item.label}>• {item.label} — {item.localDate}</p>)}</div> : null}</div> }
function Timeline({ cards, loading }: { cards: Card[]; loading: boolean }) { return <div className="overflow-auto p-7 sm:p-10"><h1 className="text-3xl font-semibold tracking-[-.05em]">Your timeline</h1><p className="mt-2 text-sm text-muted-foreground">A chronological view derived locally from your work cards.</p><div className="relative mt-9 max-w-4xl border-l border-border pl-8">{loading ? <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /> : cards.map((card) => <article key={card.windowId} className="relative mb-5 rounded-2xl border border-border bg-card p-4 before:absolute before:-left-[37px] before:top-5 before:h-3 before:w-3 before:rounded-full before:border-[3px] before:border-background before:bg-primary"><time className="text-xs text-muted-foreground">{new Date(card.startTime).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} – {new Date(card.endTime).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time><div className="mt-1 flex gap-3"><div className="min-w-0 flex-1"><b>{card.title}</b><p className="mt-1 text-sm text-muted-foreground">{card.summary}</p></div><span className="h-fit rounded-full bg-primary-muted px-2 py-1 text-[10px] text-primary">{card.status}</span></div><p className="mt-3 text-xs text-muted-foreground">{card.applications.join(" · ")}</p></article>)}</div></div> }
function HistoryPage({ sessions, onOpen }: { sessions: ChatSession[]; onOpen: (sessionId: string) => void }) { return <div className="overflow-auto p-7 sm:p-10"><h1 className="text-3xl font-semibold tracking-[-.05em]">Chat history</h1><p className="mt-2 text-sm text-muted-foreground">Conversations and their generated answers are kept locally on this device.</p><div className="mt-8 grid max-w-4xl gap-3 sm:grid-cols-2">{sessions.length ? sessions.map((session) => <button key={session.id} onClick={() => onOpen(session.id)} className="rounded-2xl border border-border bg-card p-4 text-left transition hover:border-primary/40 hover:bg-accent"><b className="block truncate text-sm">{session.title}</b><p className="mt-2 text-xs text-muted-foreground">Last updated {new Date(`${session.updatedAt}Z`).toLocaleString()}</p></button>) : <p className="text-sm text-muted-foreground">No conversations yet.</p>}</div></div> }
function SettingsPage({ recording, toggling, onToggle, screenshots, onScreenshot, screenshotBusy, userName, userEmail, onLogout, loggingOut, version }: { recording: boolean; toggling: boolean; onToggle: () => void; screenshots: boolean; onScreenshot: (value: boolean) => void; screenshotBusy: boolean; userName: string; userEmail: string; onLogout: () => void; loggingOut: boolean; version: string }) { return <div className="overflow-auto p-7 sm:p-10"><div className="max-w-2xl"><h1 className="text-3xl font-semibold tracking-[-.05em]">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Control capture and your local Dystil experience.</p><div className="mt-8 overflow-hidden rounded-2xl border border-border bg-card"><div className="flex items-center gap-4 border-b border-border p-5"><div className="flex-1"><b className="text-sm">Local capture</b><p className="mt-1 text-xs text-muted-foreground">{recording ? "Dystil is recording locally." : "Dystil is paused. Resume when you are ready."}</p></div><Button onClick={onToggle} disabled={toggling} variant={recording ? "outline" : "default"} className="rounded-xl">{toggling ? <Loader2 className="h-4 w-4 animate-spin" /> : recording ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}{recording ? "Pause" : "Resume"}</Button></div><div className="flex items-center gap-4 border-b border-border p-5"><div className="flex-1"><b className="text-sm">Capture screenshots</b><p className="mt-1 text-xs text-muted-foreground">Off by default. Accessibility-only capture remains available.</p></div>{screenshotBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Switch checked={screenshots} onCheckedChange={onScreenshot} />}</div><div className="flex items-center gap-4 p-5"><div className="flex-1"><b className="text-sm">Account</b><p className="mt-1 text-xs text-muted-foreground">{userName} · {userEmail}</p></div><Button variant="outline" onClick={onLogout} disabled={loggingOut} className="rounded-xl">{loggingOut ? <Loader2 className="h-4 w-4 animate-spin" /> : "Sign out"}</Button></div></div>{version && <p className="mt-4 text-xs text-muted-foreground">Dystil v{version}</p>}</div></div> }
