[package]
name = "dystil-protocol"
version = { workspace = true }
authors = { workspace = true }
description = "Shared serde DTOs for Dystil wire protocols."
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
hex = "0.4"
